=== anischeikh/pacman_jeu/Content/src/data/xsd/gameHistory.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Games">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Game" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="PlayerName" type="xs:string"/>
                            <xs:element name="GameDate" type="xs:dateTime"/>
                            <xs:element name="Score" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== anischeikh/pacman_jeu/bin/Debug/net8.0/src/data/xml/gameHistory.xml
<?xml version="1.0" encoding="UTF-8"?>
<Games xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../xsd/gameHistory.xsd">
    <Game>
        <PlayerName>Paul</PlayerName>
        <GameDate>2024-12-18 5:45:00</GameDate>
        <Score>1500</Score>
    </Game>
    <Game>
        <PlayerName>Marie</PlayerName>
        <GameDate>2024-12-19 16:30:00</GameDate>
        <Score>2000</Score>
    </Game>
    <Game>
        <PlayerName>Jean</PlayerName>
        <GameDate>2024-12-20 18:00:00</GameDate>
        <Score>1200</Score>
    </Game>
</Games>
